import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ResponsiveSidebar from "@/components/ResponsiveSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen">
          <div>
            <ResponsiveSidebar />
          </div>
          <main className="flex-1 overflow-y-auto p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
